Repository PharmQuest/BE, pull requests merged in 2025-01, with the labels that each got.

#2 [DOCS] 이슈,PR 템플릿
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#4 feat : 다른 테이블 연결 기초 로직 추가 mysql 테이블 생성
  src/main/java/com/pharmquest/pharmquest/medicine/domain/Medicine.java
  src/main/java/com/pharmquest/pharmquest/mypage/domain/MedicineScrap.java
  src/main/java/com/pharmquest/pharmquest/mypage/domain/PharmacyScrap.java
  src/main/java/com/pharmquest/pharmquest/mypage/domain/PostScrap.java
  src/main/java/com/pharmquest/pharmquest/mypage/domain/SupplementScrap.java
  src/main/java/com/pharmquest/pharmquest/pharmacy/domain/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/post/domain/Post.java
  src/main/java/com/pharmquest/pharmquest/supplements/domain/Supplements.java
  src/main/java/com/pharmquest/pharmquest/user/domain/User.java
  src/main/resources/application.properties
  src/main/resources/application.yml.example
Labels: ⚙ Setting

#12 feat : 공통 응답 처리 작성
  build.gradle
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/ApiResponse.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/BaseCode.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/BaseErrorCode.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/ReasonDTO.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/exception/GeneralException.java
  src/main/java/com/pharmquest/pharmquest/common/apiPayload/exception/handler/CommonExceptionHandler.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/domain/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/MedicineScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PharmacyScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PostScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/SupplementScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/domain/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/post/domain/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/domain/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/user/domain/User.java
Labels: ✨ Feature

#13 [FEAT] medicine OPENAPI 정보 연결
  build.gradle
  src/main/java/com/pharmquest/pharmquest/medicine/config/SwaggerConfig.java
  src/main/java/com/pharmquest/pharmquest/medicine/config/WebClientConfig.java
  src/main/java/com/pharmquest/pharmquest/medicine/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/medicine/dto/MedicineResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/medicine/repository/MedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/medicine/service/MedicineServiceImpl.java
Labels: ✨ Feature

#16 네이버쇼핑 openapi 영양제 정보 로드
  build.gradle
  src/main/java/com/pharmquest/pharmquest/domain/supplements/config/NaverShoppingConfig.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/domain/Enums/Nation.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/domain/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/NaverShoppingService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/NaverShoppingServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/resources/application.yml.example
Labels: ✨ Feature

#19 [Refactor] medicine 도메인 계층에 맞게 수정
  build.gradle
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/enums/Enum.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/apipayload.java
  src/main/java/com/pharmquest/pharmquest/global/auth/auth.java
  src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/WebClientConfig.java
  src/main/java/com/pharmquest/pharmquest/global/validation/validation.java
  src/main/java/com/pharmquest/pharmquest/mypage/domain/MedicineScrap.java
Labels: 🔨 Refactor

#26 feat : 소셜 로그인 기능 구현(Google)
  build.gradle
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/MedicineScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PharmacyScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PostScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/SupplementScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/domain/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/domain/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
  src/main/java/com/pharmquest/pharmquest/domain/user/repository/UserRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/IndexController.java
  src/main/java/com/pharmquest/pharmquest/global/auth/PrincipalDetails.java
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/WebMvcConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/oauth/PrincipalOauth2UserService.java
  src/main/java/com/pharmquest/pharmquest/global/config/oauth/provider/GoogleUserInfo.java
  src/main/java/com/pharmquest/pharmquest/global/config/oauth/provider/KakaoUserInfo.java
  src/main/java/com/pharmquest/pharmquest/global/config/oauth/provider/NaverUserInfo.java
  src/main/java/com/pharmquest/pharmquest/global/config/oauth/provider/OAuth2UserInfo.java
  src/main/resources/templates/index.html
  src/main/resources/templates/loginForm.html
Labels: ✨ Feature

#34 영양제 정보 정제 및 검색 기능 구현
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Advertisement.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Category.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/enums/Nation.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/domain/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/CategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/CrawlProductService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/CrawlProductServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/NaverShoppingService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/NaverShoppingServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/config/NaverShoppingConfig.java
Labels: ✨ Feature

#37 [Feat] 게시글 검색 기능 구현
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PostScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/PostCategory.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/ReportType.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostReport.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/specification/PostSpecification.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
Labels: ✨ Feature

#41 [상비약] 상비약 정보 번역작업
  build.gradle
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Labels: ✨ Feature

#44 [FEAT] : 단일 약 전체 정보 조회 (개발 확인용)
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Labels: ✨ Feature

#46 [상비약] 이미지Uri 추가
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Labels: ✨ Feature

#48 [상비약] 구조로직
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Labels: 🔨 Refactor

#50 [Feat] 게시글 좋아요 생성, 취소 및 스크랩 생성, 취소 구현
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PostScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostLikeConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostScrapConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostLike.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostReport.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Labels: ✨ Feature

#60 [Refactor] Post 기능 토큰 사용으로 리팩토링
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/Country.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/token/JwtUtil.java
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#57 DailyMed 영양제 정보 연동 및 정제
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Category.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsCategory.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/CategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Category/CategorySaveService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Category/CategorySaveServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Naver/NaverShoppingService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Naver/NaverShoppingServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/DailyMedController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/DailyMedResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: ✨ Feature

#58 [Feat] 스크랩된 약국 조회 & 로그인 관련 수정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/PharmacyScrapConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PharmacyScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/ScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/ScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/ScrapResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/domain/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/PharmacyRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/SuccessStatus.java
Labels: ✨ Feature, 🔨 Refactor

#63 [Feat] 스크랩한 영양제 조회 기능 구현
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/data/MedicineScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/data/PostScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/data/SupplementScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostScrapConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
Labels: ✨ Feature

#64 [Feat] 메인화면 게시글 조회 - 스크랩 수 조회 방식 변경, 중복 방지
  src/main/java/com/pharmquest/pharmquest/domain/home/converter/HomePostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/home/repository/HomePostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/home/response/HomePostsResponse.java
  src/main/java/com/pharmquest/pharmquest/domain/home/service/HomePostService.java
  src/main/java/com/pharmquest/pharmquest/domain/home/web/controller/HomePostController.java
  src/main/java/com/pharmquest/pharmquest/domain/home/web/dto/HomePostResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
Labels: ✨ Feature

#67 feat : cicd 기초 코드 확인
  .github/workflows/dev_deploy.yml
Labels: 🌏 Deploy

#69 fix : 배포 build 오류 수정
  .github/workflows/dev_deploy.yml
Labels: 🐞 BugFix

#72 fix : 버전 변경
  .github/workflows/dev_deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#75 fix : 번역 json 경로 yml에 등록
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
Labels: 🐞 BugFix, 🌏 Deploy

#77 ref : 번역 서비스 json경로 로컬,배포 모두 고려
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
Labels: 🐞 BugFix, 🌏 Deploy

#90 ref : dev->main test
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
Labels: 🌏 Deploy

#94 [상비약] 리스트 조회
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#97 [Refactor] 약국 조회 api 수정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/ScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/ScrapResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/converter/PlaceIdConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/enums/PharmacyCountry.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/PharmacyRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Labels: 🔨 Refactor

#99 [REFACTOR] 마이페이지 코드 리팩토링
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/PharmacyScrapConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/ScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/ScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/ScrapResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/IndexController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/loginForm.html
Labels: 🔨 Refactor

#106 fix : yml에 rds 연결 수 조정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/PharmacyScrapConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/ScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/ScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/ScrapResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/converter/PlaceIdConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/enums/PharmacyCountry.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/PharmacyRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/IndexController.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/templates/index.html
  src/main/resources/templates/loginForm.html
Labels: 🐞 BugFix, 🌏 Deploy

#105 [Feat] 게시글 신고기능(신고 수 30 이상이면 게시글 삭제)
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostReportConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/ReportType.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/report/PostReportService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/report/PostReportServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/specification/PostSpecification.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Labels: ✨ Feature

#103 refactor: api 관련 코드 패키지화 및 구조 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsCategory.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🔨 Refactor

#111 [Feat] 게시글 수정 삭제 구현
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/PostHandler.java
Labels: ✨ Feature

#110 연관된 영양제 로드 + jwtUtil 적용(풀 충돌 오류 해결)
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryKeyword.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Labels: 🐞 BugFix, ✨ Feature

#113 feat : 약국 장소 번역
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/enums/PharmacyCountry.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
Labels: ✨ Feature

#114 [상비약] 단일정보, 리스트 조회 openAPI에서 db 연결
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/config/WebClientConfig.java
Labels: ✨ Feature, 🔨 Refactor

#117 [deploy] update
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/enums/PharmacyCountry.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostReportConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/ReportType.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/report/PostReportService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/report/PostReportServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/specification/PostSpecification.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryKeyword.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsCategory.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/PostHandler.java
  src/main/java/com/pharmquest/pharmquest/global/config/WebClientConfig.java
Labels: 🌏 Deploy

#118 [Feat] 한국 영양제 정보 로드 및 dailyMed 저장 정보 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Naver/NaverShoppingServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: ✨ Feature, 🔨 Refactor

#127 [Feat] 스크랩한 영양제 카테고리 기능 추가
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
Labels: ✨ Feature

#129 [Refactor] 한국 데이터 직접 추가로 인한 카테고리 및 세부사항 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Advertisement.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryKeyword.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🔨 Refactor

#130 [Feat] 스크랩한 약국 조회 페이징 & 응답 데이터 변경
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature, 🔨 Refactor

#133 [deploy] 1월 31일 기준 dev update 반영
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Advertisement.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryKeyword.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Naver/NaverShoppingServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Labels: 🌏 Deploy

#135 [Fix] merge 후 발생한 오류 해결
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
Labels: 🐞 BugFix

#136 fix : mypage관련 build오류 수정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
Labels: 🌏 Deploy

#137 [Refactor] 신고 타입 수정, 게시글 상세 정보 수정
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/ReportType.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostReport.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/report/PostReportServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Labels: 🔨 Refactor
