Repository PharmQuest/BE, pull requests merged in 2025-02, with the labels that each got.

#139 [FEAT] 소셜 로그인 Redirect Url 응답 방식 수정
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/OAuthLoginSuccessHandler.java
Labels: ✨ Feature

#142 [Deploy] s3 사진 등록 조회 기본로직
  build.gradle
  src/main/java/com/pharmquest/pharmquest/global/config/AwsS3Config.java
  src/main/java/com/pharmquest/pharmquest/global/data/S3File.java
  src/main/java/com/pharmquest/pharmquest/global/repository/S3FileRepository.java
  src/main/java/com/pharmquest/pharmquest/global/service/S3Service.java
  src/main/java/com/pharmquest/pharmquest/global/web/controller/S3Controller.java
Labels: 🌏 Deploy, ✨ Feature

#143 [배포]s3 업로드, db저장, get 기본로직으로 확인
  build.gradle
  src/main/java/com/pharmquest/pharmquest/global/config/AwsS3Config.java
  src/main/java/com/pharmquest/pharmquest/global/data/S3File.java
  src/main/java/com/pharmquest/pharmquest/global/repository/S3FileRepository.java
  src/main/java/com/pharmquest/pharmquest/global/service/S3Service.java
  src/main/java/com/pharmquest/pharmquest/global/web/controller/S3Controller.java
Labels: 🌏 Deploy

#144 [s3] 활용 목적 주석추가
  src/main/java/com/pharmquest/pharmquest/global/data/S3File.java
  src/main/java/com/pharmquest/pharmquest/global/repository/S3FileRepository.java
  src/main/java/com/pharmquest/pharmquest/global/service/S3Service.java
  src/main/java/com/pharmquest/pharmquest/global/web/controller/S3Controller.java
Labels: 🔨 Refactor

#147 [Refactor] 게시글 조회 시 인기순(스크랩순) 정렬
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
Labels: 🔨 Refactor

#148 [배포] 20250202 dev update
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/global/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/pharmquest/pharmquest/global/data/S3File.java
  src/main/java/com/pharmquest/pharmquest/global/repository/S3FileRepository.java
  src/main/java/com/pharmquest/pharmquest/global/service/S3Service.java
  src/main/java/com/pharmquest/pharmquest/global/web/controller/S3Controller.java
Labels: 🌏 Deploy

#150 [Feat] 스크랩된 약국 목록 이미지 처리
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
Labels: ✨ Feature

#156 [FEAT] 나의 활동(게시글) 기능 구현
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
Labels: ✨ Feature

#161 Feature/post/#160
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentReportService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentReportServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
Labels: ✨ Feature

#162 [FEAT] 나의 활동 - 내가 작성한 댓글 조회 기능 구현
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
Labels: ✨ Feature

#166 [Refactor] 약국 스크랩 기능 수정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/ImageUtil.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/enums/PharmacyCountry.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Labels: 🔨 Refactor

#171 [FEAT] 유저 정보 반환 기능 구현
  src/main/java/com/pharmquest/pharmquest/domain/user/repository/UserRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/user/service/UserService.java
  src/main/java/com/pharmquest/pharmquest/domain/user/service/UserServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/UserController.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/dto/UserDTO.java
Labels: ✨ Feature

#170 [FEAT] 광고 배너 구현
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryKeyword.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/AdvertisementRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/CrawlProductService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/CrawlProductServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/AdvertisementController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/DailyMedController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/AdResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#173 [상비약] 스크랩 토큰처리
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/data/MedicineScrap.java
Labels: ✨ Feature

#174 2025-02-04update, s3, 댓글,스크랩 추가
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/data/MedicineScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/ImageUtil.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/enums/PharmacyCountry.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/GooglePlaceDetailsResponse.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostLikeConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostReportConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostScrapConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/Comment.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/CommentLike.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/CommentReport.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentLikeService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentLikeServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentReportService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentReportServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryKeyword.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/AdvertisementRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/CrawlProductService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/CrawlProductServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/AdvertisementController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/DailyMedController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/AdResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/user/repository/UserRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/user/service/UserService.java
  src/main/java/com/pharmquest/pharmquest/domain/user/service/UserServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/UserController.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/dto/UserDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/CommentHandler.java
Labels: 🌏 Deploy

#176 feat : 상비약 카테고리, 증상 키워드 검색
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Labels: ✨ Feature

#178 [Refactor] 리스트, 검색 응답형태 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🔨 Refactor

#179 20250204 update 상지약, 영양제 리스트
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🌏 Deploy

#181 [Feat] 스크랩된 약국 조회 응답값 추가
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
Labels: ✨ Feature

#183 [Feat] 약국 저장 여부 확인
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/PharmacyResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/SuccessStatus.java
Labels: ✨ Feature

#192 [Feat] 상비약 스크랩 조회
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/token/web/controller/TokenController.java
Labels: ✨ Feature

#194 Refactor/post/#191
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
Labels: 🔨 Refactor

#195 [REFACTOR] 필터링 시 연관 키워드에 관한 결과 동시 제공
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryGroup.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🔨 Refactor

#197 2025-02-06 update
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineScrapController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/PharmacyResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryGroup.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/token/web/controller/TokenController.java
  src/main/java/com/pharmquest/pharmquest/domain/user/service/UserServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/dto/UserDTO.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/SuccessStatus.java
Labels: 🌏 Deploy

#200 [상비약] 검색 전체 수 반환, page시작 1부터
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Labels: 🔨 Refactor

#201 2025-02-06 update
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Labels: 🌏 Deploy

#202 ref : openAPI dto 수정
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Labels: 🔨 Refactor

#204 ref : dto 누락 추가
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineOpenapiResponseDTO.java
Labels: 🔨 Refactor

#205 fix : dto누락 추가
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineOpenapiResponseDTO.java
Labels: 🌏 Deploy

#206 [Refactor] 유효하지 않은 토큰 에러 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
Labels: 🔨 Refactor

#210 Feature 상비약 조회 카테고리 한글, swagger 설명, db 리셋
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/enums/MedicineCategory.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineOpenapiResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Labels: ✨ Feature

#211 2025-02-07 update
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/enums/MedicineCategory.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineOpenapiResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/SuccessStatus.java
Labels: 🌏 Deploy

#215 [FEAT] 상비약 페이지네이션 추가, 상세조회 pk 변경
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListResponseDTO.java
Labels: ✨ Feature

#216 [deploy] 2025-02-08
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/BestPost.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/bestPost/BestPostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Labels: 🌏 Deploy

#218 ref : MedicineId로 이름 수정
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Labels: 🌏 Deploy

#219 [Bug] 영양제 스크랩 - 동시성 이슈
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
Labels: 🐞 BugFix

#221 [Refactor] 영양제 검색 - 응답형태 제거 및 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🔨 Refactor

#223 update 2025-02-09 영양제 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🌏 Deploy

#224 [Feat] 스크랩된 영양제 코드 수정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
Labels: ✨ Feature

#229 [Refactor] 약국 스크랩 코드 리팩토링
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/SuccessStatus.java
Labels: 🔨 Refactor

#231 [FEAT] 영양제 스크랩 조회 코드 수정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
Labels: ✨ Feature

#232 [Refactor] 스크랩 약국 조회 방식 변경
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/ImageUtil.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/repository/PharmacyRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
Labels: 🔨 Refactor

#234 [FIX] 마이페이지(나의 활동) 버그 수정
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/Comment.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
Labels: 🐞 BugFix, ✨ Feature

#236 feat : 메인화면 게시글 최신순으로 조회
  src/main/java/com/pharmquest/pharmquest/domain/home/repository/HomePostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/home/service/HomePostService.java
Labels: ✨ Feature

#240 feat : 상비약 정보 반환시 스크랩 여부 추가
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Labels: ✨ Feature

#241 2025 02 13 update 약국 스크랩, 예외처리 | 메인화면 최신순 | 상비약 스크랩 조회 반환
  src/main/java/com/pharmquest/pharmquest/domain/home/repository/HomePostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/home/service/HomePostService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryServiceImpl.java
Labels: 🌏 Deploy

#243 [Refactor] 선택 카테고리 추가 반환(검색, 조회, 스크랩)
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
Labels: 🔨 Refactor

#246 [Refactor] 약국 스크랩&조회 성능 개선
  src/main/java/com/pharmquest/pharmquest/PharmquestApplication.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/repository/PharmacyRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#248 시간 null 저장 수정 및 오타 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/config/JpaAuditingConfig.java
Labels: 🔨 Refactor

#250 feat : 상비약 스크랩 로그인 여부에 따른 반환관 처리
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineScrapService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineSaveDetailResponseDTO.java
Labels: 🔨 Refactor

#252 [Refactor] 영양제 반환 시 광고 추가 반환 구현
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Advertisement.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/AdvertisementController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/AdResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🔨 Refactor

#253 2025-02-15 update 영양제 반환 형태 광고 추가
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Advertisement.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/AdvertisementController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/AdResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Labels: 🌏 Deploy

#256 [DEPLOY] 도메인 연결
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Labels: 🌏 Deploy

#257 2025-02-16 update
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Labels: 🌏 Deploy

#259 [Refactor] 검색 기능에 country 전체 선택 추가
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/Country.java
  src/main/java/com/pharmquest/pharmquest/domain/post/specification/PostSpecification.java
Labels: 🔨 Refactor

#261 [Refactor] 베스트 게시글 로그인 없이 조회 수정
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
Labels: 🔨 Refactor

#263 ref : https 로 cors 에러 변경
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Labels: 🌏 Deploy

#264 2025-02-16 update 게시판, cors 코드 https반영
  src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/Country.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/specification/PostSpecification.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Labels: 🌏 Deploy

#265 ref : swagger config https 반영 수정
  src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Labels: 🐞 BugFix, 🌏 Deploy

#266 ref : swagger config https 반영 수정
  src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Labels: 🐞 BugFix, 🌏 Deploy

#267 [Refactor] 카테고리 관련 N+1 문제 해결 및 광고 반환 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
Labels: 🔨 Refactor

#268 [Feat] 약국 이미지 주기적 업데이트
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/ImageUtil.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/repository/PharmacyRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyS3UpdateService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
Labels: ✨ Feature

#270 [Fix] 약국 스크랩 오류 해결 & api 호출 횟수 감소
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
Labels: 🐞 BugFix, 🔨 Refactor

#271 ref : 백엔드 서브도메인으로 변경
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Labels: 🌏 Deploy, 🔨 Refactor

#272 2025-02-17 update 약국,카테고리, 배포 서브도메인 변경
  src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/ImageUtil.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/repository/PharmacyRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyS3UpdateService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Labels: 🌏 Deploy

#273 ref : 서브 도메인 변경 config변경
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Labels: 🐞 BugFix, 🌏 Deploy

#274 config변경
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Labels: 🐞 BugFix, 🌏 Deploy

#275 ref : local cors 수정
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Labels: 🐞 BugFix

#278 스크랩 관련 성능 강화 및 CorsConfig PATCH 추가
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Labels: 🔨 Refactor

#281 [FEAT] 스크랩된 영양제 응답 추가
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
Labels: 🐞 BugFix, ✨ Feature

#282 bug: 연관 영양제 이름, 국가 반환 오류 수정
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
Labels: 🐞 BugFix

#284 2025-02-19 update 스크랩 응답추가, 스크랩 성능 해결
  src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Labels: 🌏 Deploy

#286 bug: securityConfig 메서드 PATCH 추가
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#289 ref: config 파일 main과 dev 동기화
  src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
  src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#292 [Refactor] 게시글 상세정보에 신고여부 추가
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Labels: 🔨 Refactor

#295 2025-02-20 update
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/KoreanMedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/enums/Enum.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/KoreanMedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/KoreanMedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineTestController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/KoreanMedicineResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Labels: 🌏 Deploy

#300 [Feat] 임시 로그인
  src/main/java/com/pharmquest/pharmquest/domain/user/repository/UserRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/TempLoginController.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/TempLoginHandler.java
Labels: ✨ Feature

#303 ref : 필터링 값 인식 변경
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
Labels: ✨ Feature

#304 ref : 필터링 값 인식 변경
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/bestPost/BestPostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostService.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
  src/main/java/com/pharmquest/pharmquest/domain/user/repository/UserRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/TempLoginController.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/TempLoginHandler.java
Labels: 🌏 Deploy, 🔨 Refactor

#307 ref: 리스트 중복 반환 오류 해결
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/CategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Category/CategorySaveService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Category/CategorySaveServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/AdvertisementController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/AdResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
Labels: 🔨 Refactor

#308 2025-02-20 update 리스트 항목 중복 반환 버그 해결
  src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Supplements.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsScrap.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/CategoryRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Category/CategorySaveService.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Category/CategorySaveServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/AdvertisementController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/AdResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapRequestDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
Labels: 🌏 Deploy

#311 [Refactor] 임시 로그인 유저 정보 변경
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/TempLoginHandler.java
Labels: 🔨 Refactor

#316 ref : 국가 필터링 추가 enum string인식 문제 해결
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/TempLoginHandler.java
Labels: 🌏 Deploy

#318 ref : 페이지 네이션 수정
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
Labels: 🌏 Deploy

#326 [ Fix] 게시글 상세조회 N+1 문제 해결 중 발생한 문제 해결
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#327 [상비약] 한국약 저장
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/KoreanMedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/KoreanMedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/KoreanMedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineTestController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/KoreanMedicineResponseDTO.java
Labels: 🔨 Refactor

#328 2025-02-21 updated |refactor: 신고한 댓글 처리 | 한국약 저장
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/KoreanMedicineConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/KoreanMedicineRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/service/KoreanMedicineService.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineTestController.java
  src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/KoreanMedicineResponseDTO.java
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentReportRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
  src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
Labels: 🌏 Deploy

#329 [Refactor] 약국 스크랩 동시성 문제 해결
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/repository/PharmacyRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandService.java
  src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#332 ref : 미국 usa로 변경
  src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
Labels: 🌏 Deploy

#334 [Refactor] 게시글 오류 해결
  src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
  src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
  src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
Labels: 🔨 Refactor
